# 服务配置
server:
  port: 8081
  servlet:
    context-path: /user
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Spring配置
spring:
  application:
    name: user-service
  profiles:
    active: @spring.profiles.active@
  
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/biobt_user?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
      username: dba
      password: dba123
      
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      
      # 监控配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      
      # SQL监控
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          config:
            multi-statement-allow: true

  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-idle: 10
          min-idle: 5
          max-wait: 2000ms

  # Jackson配置
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      update-strategy: NOT_NULL
      insert-strategy: NOT_NULL
      select-strategy: NOT_EMPTY
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.biobt.user.domain.entity

# 分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# Nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: biobt-platform
        group: DEFAULT_GROUP
        metadata:
          version: 1.0.0
          region: cn-hangzhou
      config:
        server-addr: localhost:8848
        namespace: biobt-platform
        group: DEFAULT_GROUP
        file-extension: yml
        shared-configs:
          - data-id: common-config.yml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: database-config.yml
            group: DEFAULT_GROUP
            refresh: true
          - data-id: redis-config.yml
            group: DEFAULT_GROUP
            refresh: true

# Feign配置
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 10000
        logger-level: basic
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: false
  okhttp:
    enabled: true

# RocketMQ配置
rocketmq:
  name-server: localhost:9876
  producer:
    group: user-service-producer
    send-message-timeout: 3000
    retry-times-when-send-failed: 3
    max-message-size: 4194304
  consumer:
    group: user-service-consumer
    consume-timeout: 15000
    max-reconsume-times: 3

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

# 日志配置
logging:
  level:
    com.biobt: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.mybatis: DEBUG
    com.alibaba.druid: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n"
  file:
    name: logs/${spring.application.name}.log
    max-size: 100MB
    max-history: 30

# Swagger文档配置
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: user
      display-name: 用户管理
      paths-to-match: /api/users/**
    - group: auth
      display-name: 认证授权
      paths-to-match: /api/auth/**

# Knife4j配置
knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  production: false

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/biobt_user_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

logging:
  level:
    root: INFO
    com.biobt: DEBUG

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    druid:
      url: jdbc:mysql://test-mysql:3306/biobt_user_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true

  data:
    redis:
      host: test-redis

rocketmq:
  name-server: test-rocketmq:9876

logging:
  level:
    root: WARN
    com.biobt: INFO

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    druid:
      url: jdbc:mysql://prod-mysql:3306/biobt_user_prod?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
      stat-view-servlet:
        enabled: false

  data:
    redis:
      host: prod-redis

rocketmq:
  name-server: prod-rocketmq:9876

knife4j:
  production: true

logging:
  level:
    root: WARN
    com.biobt: WARN
  file:
    name: /app/logs/${spring.application.name}.log