server:
  port: 8084

spring:
  application:
    name: workflow-engine
  
  profiles:
    active: dev
  
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biobt_workflow?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: biobt_app
    password: biobt123456
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: WorkflowHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  # Redis配置
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      database: 2
      timeout: 6000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
  
  # Nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: biobt-platform
        group: DEFAULT_GROUP
      config:
        server-addr: localhost:8848
        namespace: biobt-platform
        group: DEFAULT_GROUP
        file-extension: yaml

# Flowable工作流配置
flowable:
  # 数据库配置
  database-schema-update: true
  db-history-used: true
  
  # 流程引擎配置
  process:
    definition-cache-limit: 10000
  
  # 异步执行器配置
  async:
    executor:
      default-async-job-acquire-wait-time: 10000
      default-timer-job-acquire-wait-time: 10000
  
  # REST API配置
  rest:
    app:
      authentication-mode: verify-privilege

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized

# 日志配置
logging:
  level:
    com.biobt.workflow: DEBUG
    org.flowable: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n"
  file:
    name: logs/workflow-engine.log

# API文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: 工作流引擎API
    description: BioBt平台工作流引擎服务API文档
    version: 1.0.0
    contact:
      name: BioBt Platform Team
      email: dev@biobt.com

# 工作流引擎配置
workflow:
  # 流程定义存储路径
  process-definition-path: classpath:processes/
  
  # 任务分配策略
  task-assignment:
    default-assignee: system
    auto-claim: false
  
  # 流程监控配置
  monitoring:
    enabled: true
    metrics-enabled: true
  
  # 流程缓存配置
  cache:
    process-definition-cache-size: 1000
    deployment-cache-size: 500